github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/luxuretv-downloader",
  "https://serp.co/products/luxuretv-downloader/reviews/",
  "https://extensions.serp.co/luxuretv-downloader",
  "https://browserextensions.io/luxuretv-downloader"
]
